### ISSUE TITLE
Glitch whole canvas?

### ISSUE THREAD

**Issue by paul-uz** [ffd8/p5.glitch#8]
Is there a way I can glitch the entire canvas rather than an image or webcam capture?

**Comment by ffd8** [comment]
@paul-uz – yupyup of course, you just need to do a `get(0, 0, width, height)` to grab the whole screen, then feed that into the `glitch.loadImage()` function. Warning, it gets veeery stroboscopic, since it's feeding on itself. A better approach is probably to create a layer to draw your shapes onto, using `createGraphics()`, then feed that into the `glitch.loadImage()` function.

Here's an example for the whole canvas:
```js
let glitch

function setup() {
	createCanvas(windowWidth, windowHeight)

	glitch = new Glitch(this)
	glitch.pixelate(1)
	glitch.errors(false)
	glitch.loadQuality(.9)
	imageMode(CENTER)
}

function draw() {

	circle(mouseX, mouseY, 50)
	
	if(frameCount % 3 === 0) {
		let getCanvas = get(0, 0, width, height)
		// getCanvas.resize(width/4, 0)
		
		glitch.loadImage(getCanvas)
		
		glitch.randomBytes(1)

		glitch.buildImage()
		image(glitch.image, width / 2, height / 2, glitch.width, glitch.height)
	}
}
```

here's a snippet using the layer approach:

```js
let glitch, layer

function setup() {
	createCanvas(windowWidth, windowHeight)

	glitch = new Glitch(this)
	glitch.pixelate(1)
	glitch.errors(false)
	glitch.loadQuality(.9)
	imageMode(CENTER)
	
	layer = createGraphics(width, height)
}

function draw() {

	layer.circle(mouseX, mouseY, 50)
	
	if(frameCount % 3 === 0) {
		glitch.loadImage(layer)
		
		glitch.randomBytes(1)

		glitch.buildImage()
		image(glitch.image, width / 2, height / 2, glitch.width, glitch.height)
	}
}
```

**Comment by paul-uz** [comment]
I'll give it a go thanks!

**Comment by ffd8** [comment]
Hope it worked!
Closing – feel free to re-open if needed or add further discussion here.
